spring:
  security:
    user:
      name: user
      password: siheca
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_control
    username: postgres
    password: mich2021$
    driver-class-name: org.postgresql.Driver
  logging:
    level:
      org.springframework.security: DEBUG
  jpa:
    hibernate:
      ddl-auto: update # Opciones: none, validate, update, create, create-drop
    show-sql: true # Muestra las consultas SQL en la consola
  # Opcional: Puedes agregar más configuraciones de JPA si es necesario
